[package]
name = "gurk"
description = "Signal messenger client for terminal"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
chrono = "0.4.13"
crossterm = "0.17"
tui = { version = "0.10", default-features = false, features = ["crossterm"] }
unicode-width = "0.1.8"
textwrap = "0.12.1"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
structopt = "0.3.15"
toml = "0.5.6"
dirs = "3.0.1"
